# Generated by Django 5.2.4 on 2026-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_users',
            field=models.BooleanField(default=False),
        ),
    ]
