# Generated by Django 5.2.4 on 2026-06-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_prediction_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
