# Generated by Django 5.2.15 on 2026-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_create_advisor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_education',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
